#
# This pipeline needs the following tasks from Tekton Hub
#   - git-clone
#   - flake8
#   - buildah
#   - openshift-client
#
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
      description: The URL of the git repository
      type: string
    - name: branch
      description: The branch to clone
      type: string
      default: main
    - name: app-name
      description: The name of the application
      type: string
      default: counter-service
    - name: build-image
      description: The image to build
      type: string
      default: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/counter-service:latest
  tasks:
    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: cleanup

    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: git-clone
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)
      runAfter:
        - init

    - name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: flake8
      params:
      - name: image
        value: "python:3.9-slim"
      - name: args
        value: ["--count","--max-complexity=10","--max-line-length=127","--statistics"]
      runAfter:
        - clone

    - name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: nose
      params:
      - name: args
        value: "-v --with-spec --spec-color --with-coverage --cover-package=app"
      runAfter:
        - lint

    - name: build
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: buildah
      params:
      - name: IMAGE
        value: "$(params.build-image)"
      - name: FORMAT
        value: "oci"
      runAfter:
        - tests

    - name: deploy
      taskRef:
        name: openshift-client
      params:
      - name: SCRIPT
        value: |
          oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
      runAfter:
        - build